Q1 Swap two variables without using a third variable:

In [3]:
a = 10
b = 20
a,b = b,a
print(f"After Swapping a={a},b={b}")

After Swapping a=20,b=10


In [4]:
a = 10
b = 20
temp = a
a = b
b = temp
print(f"After Swapping a={a},b={b}")

After Swapping a=20,b=10


In [6]:
a ="this is my book"
b = a[::-1]
print(b)

koob ym si siht


In [10]:
string = "this is my book"
words = string.split()
reversed_string = " ".join(words[::-1])
print(reversed_string)

book my is this


In [11]:
list1 = [1,2,3,4,5,6]
print(list1)

tuple1 = (1,2,3,4,5,6)
print(tuple1)

# Differentiation:
# Lists are mutable (can be modified), while tuples are immutable (cannot be modified).

[1, 2, 3, 4, 5, 6]
(1, 2, 3, 4, 5, 6)


In [15]:
string = "I am a Data Scientist"
word = string.split()[3]
reversed1 = word[::-1]
print(reversed1)

ataD


In [16]:
string = "I am a Data Scientist"
word = string.split()[3][::-1]
print(word)

ataD


Q6 Create a list of odd numbers between 11-30:

In [19]:
odd_number = []
for i in range (11,20):
    if i % 2!=0 :
        odd_number.append(i)
print(odd_number)

[11, 13, 15, 17, 19]


In [22]:
import numpy as np
a1 = np.arange(27)
print(a1)
a2 = a1.reshape(3,3,3)
print(a2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
Q8 Create an array with random numbers:

In [25]:
random_no = np.random.randint(10)
print(random_no)

3


In [27]:
import random
random_integer = random.randint(1, 10)
print(random_integer)

6


In [34]:
import random
l1 = np.random.randint(1,100,size=5).tolist()
print(l1)

# or 
n = 10
l1 = np.random.randint(1,100,size=n).tolist()
print(l1)

[15, 4, 62, 62, 79]
[81, 50, 83, 99, 49, 52, 41, 93, 37, 65]
